const NOTE_TABLE_NAME = 'Notes';

const NOTES_NAME_MAX_LENGTH = 100;
const NOTES_NAME_MIN_LENGTH = 1;

const NOTES_CONTENT_MAX_LENGTH = 1000;

module.exports = {
    NOTE_TABLE_NAME,
    NOTES_NAME_MAX_LENGTH,
    NOTES_NAME_MIN_LENGTH,
    NOTES_CONTENT_MAX_LENGTH
};