const NOTES_TABLE_NAME = 'Notes';

const NOTES_TITLE_MAX_LENGTH = 100;
const NOTES_TITLE_MIN_LENGTH = 1;

const NOTES_CONTENT_MAX_LENGTH = 1000;

module.exports = {
    NOTES_TABLE_NAME,
    NOTES_TITLE_MAX_LENGTH,
    NOTES_TITLE_MIN_LENGTH,
    NOTES_CONTENT_MAX_LENGTH
};